name: Deploy to AKS

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: web

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Login to Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.{
  "clientId": "b2153d1d-47aa-443c-91d4-114c677bb459",
  "clientSecret": "gAU8Q~.Bsf8y6cNzvTUP1wdPqUGJAsdC7FucwcwC",
  "subscriptionId": "a9ac7173-ebb3-49b0-bea0-ac378cb83086",
  "tenantId": "ecb2ece6-5898-4b32-9563-29243d97ab03",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
} }}

    # Login to ACR
    - run: az acr login --name ${{ secrets.mustaacr }}

    # Build & Push (amd64 enforced)
    - name: Build and Push
      run: |
        IMAGE=${{ secrets.mustaacr }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker build --platform linux/amd64 -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    # Set AKS context
    - uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ secrets.6pm-rg }}
        cluster-name: ${{ secrets.6pmk8s }}

    # Deploy
    - name: Deploy
      run: |
        sed "s|IMAGE|$IMAGE|g" k8s/deployment.yaml | kubectl apply -f -
